/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface AnalyzeRequest {
  /** The URL to analyze */
  url: string;
}

export interface AnalysisResult {
  /** HTTP status code returned by the URL */
  httpStatus: number;
  /** Response time in milliseconds */
  responseTime: number;
  /**
     * The page title extracted from the HTML
     * @nullable
     */
  pageTitle?: string | null;
  /**
     * The meta description extracted from the HTML
     * @nullable
     */
  metaDescription?: string | null;
  /** Number of H1 elements on the page */
  h1Count: number;
  /** Number of images missing alt text */
  imagesMissingAlt: number;
  /** Approximate word count of the page body text */
  wordCount: number;
}

export interface ErrorResponse {
  /** Human-readable error message */
  error: string;
}

