/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * Fetches the given URL and returns SEO and metadata analysis
 * @summary Analyze a website URL
 */
export const AnalyzeUrlBody = zod.object({
  "url": zod.string().describe('The URL to analyze')
})

export const AnalyzeUrlResponse = zod.object({
  "httpStatus": zod.number().describe('HTTP status code returned by the URL'),
  "responseTime": zod.number().describe('Response time in milliseconds'),
  "pageTitle": zod.string().nullish().describe('The page title extracted from the HTML'),
  "metaDescription": zod.string().nullish().describe('The meta description extracted from the HTML'),
  "h1Count": zod.number().describe('Number of H1 elements on the page'),
  "imagesMissingAlt": zod.number().describe('Number of images missing alt text'),
  "wordCount": zod.number().describe('Approximate word count of the page body text')
})


